#!/usr/bin/env just --justfile

dotnet_version := "8.0.401"

set shell := ["bash", "-c"]

# run the project locally (same as "run")
default: run

# starts VS Code with appropriate environment variables to allow for debugging
code: checkdotnet
    #!/usr/bin/env bash
    # Eliminate environment variables introduced by the nix shell that interfere
    # with Aspire debugging in VS Code. See https://github.com/dotnet/aspire/issues/5389 and
    # https://github.com/dotnet/aspire/issues/5475
    export -n DIRENV_DIFF
    export -n NIX_CFLAGS_COMPILE
    export -n NIX_LDFLAGS
    export -n PYTHONPATH
    export -n name
    export -n shell
    code .

# install .NET locally if it’s not there
checkdotnet:
    [ -d .dotnet ] && [[ "$(dotnet --version)" == "{{dotnet_version}}" ]] || just installdotnet 

# install the appropriate .NET version locally
installdotnet:
    [ ! -d .dotnet ] || rm -r .dotnet 
    wget https://dot.net/v1/dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --version {{dotnet_version}} --install-dir .dotnet --no-path
    rm dotnet-install.sh
    dotnet workload install aspire

# run the project locally
run: checkdotnet
    dotnet run --project src/Placeholder.AppHost
